CREATE TABLE public."user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    is_enabled BOOLEAN                                 NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE public."user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

CREATE TABLE business
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_business PRIMARY KEY (id)
);

CREATE TABLE member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_id BIGINT,
    user_id     BIGINT,
    created     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE TABLE reservation
(
    id          UUID NOT NULL,
    name        VARCHAR(255),
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    member_id   BIGINT,
    user_id     BIGINT,
    business_id BIGINT,
    created     TIMESTAMP WITHOUT TIME ZONE,
    modified    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_USER FOREIGN KEY (user_id) REFERENCES public."user" (id);