CREATE TABLE service
(
    id          UUID NOT NULL,
    name        VARCHAR(255),
    business_id BIGINT,
    created     TIMESTAMP WITHOUT TIME ZONE,
    modified    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_service PRIMARY KEY (id)
);

ALTER TABLE service
    ADD CONSTRAINT FK_SERVICE_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);

ALTER TABLE reservation
    ADD COLUMN service_id UUID;

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service (id);

CREATE TABLE duration
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    duration BIGINT,
    business_id BIGINT,
    created  TIMESTAMP WITHOUT TIME ZONE,
    modified TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_duration PRIMARY KEY (id)
);

ALTER TABLE duration
    ADD CONSTRAINT FK_DURATION_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);